import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Text, TextInput, View } from "react-native";
import { useAuth } from "@/auth/auth-context";
import { invokeEdgeFunction } from "@/lib/backend";
import { supabase } from "@/lib/supabase";
import { BackHeader, Badge, GlassCard, PrimaryButton, Screen, SecondaryButton } from "@/components/ui";
import { useLocalSearchParams, useRouter } from "expo-router";

export function CancellationRequestWiredScreen(){const p=useLocalSearchParams<Record<string,string>>();const{user}=useAuth();const router=useRouter();const[reason,setReason]=useState("");const[busy,setBusy]=useState(false);const submit=async()=>{if(!p.attendance_id||!reason.trim())return Alert.alert("Pembatalan","Attendance ID dan alasan wajib diisi.");setBusy(true);try{const{error}=await supabase.from("cancellation_requests").insert({attendance_id:p.attendance_id,requester_id:user?.id,reason:reason.trim()});if(error)throw error;router.replace("/screens/cancellation-submitted");}catch(e){Alert.alert("Pembatalan",e instanceof Error?e.message:"Pengajuan gagal.");}finally{setBusy(false);}};return <Screen><BackHeader title="Ajukan Pembatalan"/><GlassCard><Text className="font-black">Attendance {p.attendance_id||"-"}</Text><TextInput value={reason} onChangeText={setReason} multiline placeholder="Jelaskan alasan pembatalan" className="mt-4 min-h-28 rounded-2xl border border-[#C5C8B8] bg-white px-4 py-3"/><PrimaryButton className="mt-4" disabled={busy} onPress={()=>void submit()}>{busy?<ActivityIndicator color="#FFF"/>:<Text className="font-bold text-white">Ajukan Pembatalan</Text>}</PrimaryButton></GlassCard></Screen>}

export function CancellationReviewWiredScreen(){const[items,setItems]=useState<any[]>([]);const load=async()=>{const{data}=await supabase.from("cancellation_requests").select("id,attendance_id,requester_id,reason,status,created_at").order("created_at",{ascending:false}).limit(100);setItems(data||[]);};useEffect(()=>{void load();},[]);const review=async(id:string,decision:"approved"|"rejected")=>{try{await invokeEdgeFunction("review-cancellation",{request_id:id,decision});await load();}catch(e){Alert.alert("Review",e instanceof Error?e.message:"Review gagal.");}};return <Screen><BackHeader title="Review Pembatalan"/>{items.length?items.map(x=><GlassCard key={x.id}><View className="flex-row justify-between"><Text className="font-black">{x.attendance_id}</Text><Badge tone={x.status==="approved"?"green":x.status==="rejected"?"red":"yellow"}>{x.status||"pending"}</Badge></View><Text className="mt-2 text-sm text-gray-600">{x.reason}</Text>{(!x.status||x.status==="pending")?<View className="mt-4 flex-row gap-3"><SecondaryButton className="flex-1" onPress={()=>void review(x.id,"rejected")}><Text className="font-bold text-red-700">Tolak</Text></SecondaryButton><PrimaryButton className="flex-1" onPress={()=>void review(x.id,"approved")}><Text className="font-bold text-white">Setujui</Text></PrimaryButton></View>:null}</GlassCard>):<GlassCard><Text className="font-bold">Tidak ada permintaan pembatalan.</Text></GlassCard>}</Screen>}
