alter function public.get_my_attendance_history() security definer;
alter function public.get_my_attendance_history() set search_path = '';
alter function public.get_qr_owner_details(uuid) security definer;
alter function public.get_qr_owner_details(uuid) set search_path = '';
alter function public.mark_notification_read(uuid) security definer;
alter function public.mark_notification_read(uuid) set search_path = '';
alter function public.notify_sync_delayed(uuid,uuid,uuid,text) security definer;
alter function public.notify_sync_delayed(uuid,uuid,uuid,text) set search_path = '';
alter function public.search_user_directory(text,integer) security definer;
alter function public.search_user_directory(text,integer) set search_path = '';
alter function public.server_cancel_attendance_by_owner(uuid,uuid,text) security definer;
alter function public.server_cancel_attendance_by_owner(uuid,uuid,text) set search_path = '';
alter function public.server_create_qr(uuid,text,qr_target_mode,timestamptz,timestamptz,integer,boolean,double precision,double precision,integer,uuid[]) security definer;
alter function public.server_create_qr(uuid,text,qr_target_mode,timestamptz,timestamptz,integer,boolean,double precision,double precision,integer,uuid[]) set search_path = '';
alter function public.server_delete_qr(uuid,uuid) security definer;
alter function public.server_delete_qr(uuid,uuid) set search_path = '';
alter function public.server_record_attendance(uuid,uuid,text,uuid,timestamptz,sync_status,text,text,double precision,double precision,numeric) security definer;
alter function public.server_record_attendance(uuid,uuid,text,uuid,timestamptz,sync_status,text,text,double precision,double precision,numeric) set search_path = '';
alter function public.server_review_cancellation(uuid,uuid,cancellation_status,text) security definer;
alter function public.server_review_cancellation(uuid,uuid,cancellation_status,text) set search_path = '';
alter function public.server_rotate_qr_token(uuid,uuid,interval) security definer;
alter function public.server_rotate_qr_token(uuid,uuid,interval) set search_path = '';
alter function public.server_update_qr(uuid,uuid,text,qr_target_mode,timestamptz,timestamptz,integer,boolean,double precision,double precision,integer,uuid[]) security definer;
alter function public.server_update_qr(uuid,uuid,text,qr_target_mode,timestamptz,timestamptz,integer,boolean,double precision,double precision,integer,uuid[]) set search_path = '';